### ISSUE TITLE
Jobs gtop fix

### ISSUE THREAD

**Issue by Teense** [r4g3baby/SimpleScore#40]
Hi,
would it be possible to fix the scoreboard on after entering the /jobs gtop
command and others that also use the scoreboard?
After viewing the scoreboard with another plugin, your scoreboard will not turn on.
Thanks
Tee

**Comment by r4g3baby** [comment]
Hey, I've made a few changes that should help in situations like this. Would you be willing to try it out if I send you a development version to download?

**Comment by Teense** [comment]
Yes, of course.

**Comment by r4g3baby** [comment]
Download from the link bellow and let me know how it goes.
https://wormhole.app/M7NKY#I-0efeciFJ3hF32ixZk26g

**Comment by Teense** [comment]
Better. SimpleScore always turns on again, but Scoreabord from Jobs turns on in only 50% of attempts. Here is the video

https://user-images.githubusercontent.com/78209297/161604189-cb5cd485-5f2b-4d1a-9a4a-244c334ca419.mp4

**Comment by r4g3baby** [comment]
Does it show anything on the console logs when you change between the jobs scoreboards?

**Comment by Teense** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/78209297/161641258-30c40b60-619b-418e-b88e-98d73bd00f90.png)

**Comment by r4g3baby** [comment]
It looks like that's just a poor implementation by the jobs plugin developer, right now what I'm doing is listening to packets and when a scoreboard is set in the sidebar SimpleScore will disable for that player until the current player objective is removed.

What seems to be happening is the jobs plugin is constantly creating and removing a scoreboard instead of just updating it, I'll see if there's some way I can improve to handle that but I'm not seeing an immediate solution right now.

My current fix should be able to handle 90% of the cases when it comes to plugins overriding the scoreboard but besides just completely preventing other plugins from displaying their scoreboard I don't think there's an easy fix for it atm. I'll keep looking into it and let you when I come up with something.

**Comment by Teense** [comment]
Ok, thanks for fix, it's alright.
