### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by KhrysAK47** [r4g3baby/SimpleScore#7]
Hey there! I'm using SimpleScore v3.7.0 on Paper 1.16.5, and I get this error on startup, I thought it was a issue with Gadse's plugin but no. 

The error is this one: https://pastebin.com/PNM2hLFC

Any ideas?

**Comment by r4g3baby** [comment]
Hey, that error is caused by PlaceholderAPI (or more accurately the plugin that provides the placeholder) and not SimpleScore. This is most likely due to a placeholder you are using that has some problems.
It looks like the problem comes from ``me.gadse.seasonexpansion.SeasonExpansion``,  you need to figure out which placeholder is causing the issue and remove it or ask the plugin developer for a fix/support.
